sonyxperiadev/gerrit-events

src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritHandler.java

Gerrit Trigger must create EventThreads with elevated priviledges
in order to query information about items.
This permits consumers of Gerrit Events to create their own
EventThreads.

Permit consumers to create EventThreads

---

pom.xml

The reason for this is that communication with Gerrit might be lost under
high-load situations when using recent Java7 releases.
The issue that occurs is the "verify:false" problem outlined in the
changelog for 0.1.51:
http://www.jcraft.com/jsch/ChangeLog
The actual error that will appear runs like this:
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Feb 02, 2015 2:42:20 PM com.sonymobile.tools.gerrit.gerritevents.workers.cmd.AbstractSendCommandJob sendCommand
SEVERE: Could not run command gerrit approve 60123,1 --message 'Build Successful
[...]
https://[URL]/job/[JOB]/2502/ : SUCCESS' --verified 1 --code-review 0
java.io.IOException: Error during sending command
[...]
Caused by: com.sonymobile.tools.gerrit.gerritevents.ssh.SshException: …

Updated com.jcraft.jsch to 0.1.51

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/GerritEventKeys.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/GerritEventType.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/events/ProjectCreated.java
src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritHandlerTest.java

This is needed to enable incremental update of the project list in Gerrit-Trigger. So that Gerrit-Trigger only does one initial load of the gerrit projects, and thereafter only listens to project-created events. This to prevent unnecessary polling of Gerrit.
I have a patch for this functionality, ready to upload to gerrit-trigger, but i need a release of the gerrit-events that supports it first.
project-created event was introduced to Gerrit with [1].
[1] https://gerrit-review.googlesource.com/#/c/67294/
Change-Id: I7badaa9dcbdbfb8c24c367d9eb6006fc6da7a192

Add project-created event.

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/GerritEventKeys.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/GerritEventType.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/events/PatchsetNotified.java

This patch adds patchset-notified event.
It is a extended event defined by 'Gerrit Notify PatchSet Plugin'.
https://github.com/rinrinne/gerrit-notify-patchset

Add patchset-notified event

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/ssh/SshConnectionImpl.java

The SSH client will try to connect using Kerberos authentication
when the server provides it. This will cause the client to wait till
Kerberos credentials have been filled in using the console.
This change will set the PreferredAuthentications setting to publickey
causing the client to only use publickey authentication.

Set publickey as PreferredAuthentications for the SSH connection

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/attr/RefUpdate.java
src/test/java/com/sonymobile/tools/gerrit/gerritevents/dto/attr/RefUpdatedTest.java

We need to take into consideration whether
the event contains the long or short name for Ref.
Gerrit 2.12 will no longer have short branch names in the
RefUpdated event.
Pre Gerrit 2.12
---------------
GERRIT_REFNAME = master
Gerrit 2.12
-----------
GERRIT_REFNAME = refs/heads/master

Backwards compat for RefUpdated in Gerrit 2.12

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/GerritEventKeys.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/attr/Approval.java

An upcoming Gerrit change[1] will add an 'updated' attribute
to the approvals info in Gerrit stream events. This change adds
that info to the Approval.
[1] https://gerrit-review.googlesource.com/#/c/71051

Add `updated` attribute to approval

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/GerritEventKeys.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/attr/Approval.java

Change 3627295 prematurely added support to an unmerged
gerrit stream events change[1]. That gerrit change started
out with an updated property to indicate that an approval
was updated however thru reviews that change ended up adding
an oldValue property instead. This property is used to
show the previous approval value when the score changed. Also
the property is only appended to the stream event if the
approval was changed so we can use this info to determine
whether the approval was updated.  We also deprecate `getUpdate` in
favor of `isUpdated`.
[1] https://gerrit-review.googlesource.com/#/c/71051/

Deprecate get updated

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/GerritEventKeys.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/attr/Approval.java

Change 36272952 prematurely added support to an unmerged
gerrit stream events change[1]. That gerrit change started
out with an `updated` property to indicate that an approval
was updated however thru reviews that change ended up adding
an `oldValue` property instead.  This property is used to
show the previous approval value when the score changed. Also
the property is only appended to the stream event if the
approval was changed so we can use this info to determine
whether the approval was updated.
[1] https://gerrit-review.googlesource.com/#/c/71051/

Support `oldValue` instead of `updated` property

---

pom.xml
src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritConnection.java
src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritConnectionTest.java

Hi, long time no see :)
I have had a concern about GerritConnection for a long time. Its thread is blocked by readLine(). Due to this, we had to close connection rather than channel. It made a lot of exceptions whenever disconnected.
This might solve issues around SSH connection handling.

Improve SSH command stream channel handling

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritConnection.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/ssh/SshConnection.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/ssh/SshConnectionImpl.java
src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritConnectionTest.java

InputStream generated by SSH channel may not reach EOF in illegal SSH connection state change. Due to this, GerritConnection cannot get out of the loop for reading gerrit stream.
This patch checks the state of SSH channel and connection per loop. In addition, send signal to watchdog only if stream read count is > 0 for working watchdog effectively.
Issue: #58

Get out of gerrit event stream loop in illegal state

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/rest/ReviewInput.java

To support setting tag to comments in the Gerrit Trigger plugin,
add the 'tag' field to ReviewInput class as specified in [1].
[1] https://gerrit-documentation.storage.googleapis.com/Documentation/2.13/rest-api-changes.html#review-input
[JENKINS-43904]

Add 'tag' field to ReviewInput

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritConnection.java

See https://issues.jenkins-ci.org/browse/JENKINS-44568
Signed-off-by: Sorin Sbarnea <ssbarnea@redhat.com>

Increase receive buffer size to 256KB

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritConnection.java
src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritConnectionTest.java

fix: [JENKINS-44568], [JENKINS-44414]
When a message is received that is bigger than the internal buffer, the
internal buffer position was wrongly set to the buffer capacity.
But we also can't just delete the buffer is no newline was found. So we
append what we've read in a Stringbuilder and append until we encounter a
newline.

fix: JENKINS-44568, JENKINS-44414

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritHandler.java

Extend logging in case of exception in third-party gerrit listeners. In current implementation if `NullPointerException` occurs user can see only: `Exception thrown during event handling: null` in the logs.

Print the listener and event class in case of InvocationTargetException

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritHandler.java
src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritHandlerTest.java

endsWith gives more power to system administator of Gerrit. I.e. all
bots having same postfix can be excluded at once.
The only problem that it may introduce is a key when user wants to exclude "bot@mail.com", but "robot@mail.com" got excluded as well. Should not be a big problem if we assume that all gerrit bot mails are controlled by the user as well.

Use endsWith instead of equals to blacklist mails

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritHandler.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritSendCommandQueue.java

It should simplify troubleshooting in case of slowness in event
processing logic.

Print the warning if amount of events in incoming queue is too big

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/attr/Change.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/events/TopicChanged.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/rest/Topic.java

Unfortunately, sometimes Gerrit sends empty topic field or Jenkins deserialise topic as empty string. To prevent receiving list of random changes for empty topic this change adds explicit checks.
And because we are using masked topic name (`{}`) to support spaces, commas and other things we end up in have full list of all gerrit changes (with some limit on gerrit side):
```
ssh -p PORT user@gerrit gerrit query --current-patch-set --format=JSON topic:{} | wc -l
501
```
Without mask (no entries found):
```
ssh -p PORT user@gerrit gerrit query --current-patch-set --format=JSON topic: | wc -l
1
```
So, now we forcibly switch topic/topicObject to null if name is empty and check that we don't query changes for empty topic name.

Prevent receiving list of random changes for empty topic name

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/GerritEventKeys.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/GerritEventType.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/events/HashtagsChanged.java
src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritHandlerTest.java
src/test/java/com/sonymobile/tools/gerrit/gerritevents/dto/events/HashtagsChangedTest.java
src/test/resources/com/sonymobile/tools/gerrit/gerritevents/dto/events/DeserializeHashtagsChangedTest.json

With the arrival of NoteDB[1], gerrit now supports hashtags on changes
which might open interesting use-cases, like go's use of hashtags for
managing CL[2].
This patch adds support for the hashtag changed event.
[1] https://gerrit-review.googlesource.com/Documentation/note-db.html
[2] https://github.com/golang/go/issues/24836

Add hashtags-changed event

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/GerritEventKeys.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/events/HashtagsChanged.java
src/test/java/com/sonymobile/tools/gerrit/gerritevents/dto/events/HashtagsChangedTest.java
src/test/resources/com/sonymobile/tools/gerrit/gerritevents/dto/events/DeserializeHashtagsChangedTest.json

The hashtags-changed event also includes the added and removed hashtags
on a change, which may be interesting to trigger on. This patch adds the
getAddedHashtags/getRemovedHashtags to the HashstagsChanged event.
One sample usecase would be that of an embargo'ed change which gets
built whenever the 'embargo' hashtag is removed.

hashtags: Also convey added and removed hashtags

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandler.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerWithPersistedConnection.java
src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerTest.java
src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerTestBase.java
src/test/java/com/sonymobile/tools/gerrit/gerritevents/GerritQueryHandlerWithPersistedConnectionTest.java

Recreating the SSH connection for each query may be slow.
Let's support keeping one open all the time.
My queries are 4 times faster now :D
Plan to use it from [jira-gerrit-plugin](https://github.com/MeetMe/jira-gerrit-plugin).

Cache the existing SSH connection for GerritQueryHandler

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/events/CommentAdded.java

When comparing two CommentAdded events to see if they're equal, we
should not only take the change and the patchset into account, but also
the comment that triggered the event. Override the hashCode and equals
methods in CommentAdded to check the comment in addition to the fields
already used by ChangeBasedEvent (its superclass).
Fixes #90

Also use comment equality in CommentAdded events

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/GerritEventType.java
src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/events/RerunCheck.java

The checks plugin for gerrit got a new event rerun-check[1] to signal
that a rerun is wanted. Add support for it here.
The support for gerrit-trigger-plugin can be found here: [2]
[1] https://gerrit-review.googlesource.com/c/plugins/checks/+/255373
[2] https://github.com/jenkinsci/gerrit-trigger-plugin/pull/435

Add rerun-check event

---

src/main/java/com/sonymobile/tools/gerrit/gerritevents/dto/GerritChangeKind.java

Since 2015, NO_CHANGE is a possible kind for a change. This means that only the SHA-1 differs, so even more trivial than a trivial rebase or no code change.
This should be checked by the gerrit-trigger if either exclude trivial rebase or exclude no code change is selected, thus it needs to be added here.

Added a new change kind, NO_CHANGE
